### ISSUE TITLE
Plugin is blank on profile

### ISSUE THREAD

**Issue by JonAllenTX** [Venutius/bp-xprofile-username-field#1]
I have installed this plugin and attempted to add it to xprofile base section.  When editing the profile there's nothing there.  It just has a display to change the privacy settings.  And actually, it makes all of the other custom fields after it blank.  Basically it breaks the entire xprofile plug-in after this entry.  Since it's a required entry, I cannot save any profile changes.  

WordPress Information
--
Home URL: | https://
Site URL: | https://
WP Version: | 5.1.1
WP Multisite: | –
WP Memory Limit: | 256 MB
WP Debug Mode: | No
WP Cron: | Yes
Language: | en_US
Upload Directory  Location: | https://

Server Information
Server Info: | Apache
Server IP Address: | 
Server Protocol: | bluehost.com
Server Administrator: | 
Server Web Port: | 443
CGI Version: | CGI/1.1
PHP Version: | 7.0.33
PHP Post Max Size: | 64 MB
PHP Time Limit: | 30
PHP Max Input Vars: | 1000
GD Library: | Yes, version: bundled (2.1.0 compatible)
cURL Version: | 7.64.0, OpenSSL/1.0.2r
SUHOSIN Installed: | –
MySQL Version: | 5.7.23
Max Upload Size: | 64 MB
Default Timezone is UTC: | Yes
PHP Error Log File Location: | error_log
fsockopen/cURL: | Yes
SoapClient: | Yes
DOMDocument: | Yes
GZip: | Yes
Multibyte String: | Yes
Remote Get Status: | Yes
Current Theme
Name: | Kleo Child
Version: |  
Author URL: | http://seventhqueen.com
Child Theme: | Yes
Parent Theme Name: | Kleo
Parent Theme Version: | 4.3.9
Parent Theme Author URL: | http://themeforest.net/user/SeventhQueen

Active Plugins 
Activity Reactions For Buddypress | Paramveer Singh for Arete IT Private Limited 1.0.22
Advanced iFrame | Michael Dempfle 7.6
bbPress Integration | Michael Adams and Sam Bauers 1.0
bbPress | The bbPress Community 2.5.14
BuddyPress Activity Filter | Wbcom Designs 2.0.0
BuddyPress Activity ShortCode | BuddyDev 1.1.5
BuddyPress Activity Social Share | Wbcom Designs 2.0.0
BuddyPress Create Group Types | Wbcom Designs 2.0.0
BuddyPress Favorite Notification | Wbcom Designs 1.0.4
BuddyPress Featured Members | BuddyDev 1.1.1
BuddyPress Group Live Chat | Venutius 1.2.0
BuddyPress Live Notification | BuddyDev 2.1.0
BuddyPress Member Type Generator | BuddyDev 1.0.5
(BuddyDev) BuddyPress Poke | Anu Sharma 1.1.1
BP Profile Search | Andrea Tarantini 5.0.3
BuddyPress User To-Do List | Wbcom Designs 2.0.0
BP xProfile Username Field | Venutius 0.2.5
BuddyPress to WordPress Full Sync | Envire Web Solutions 0.3.3
BuddyPress Activity Plus | WPMU DEV 1.6.4
BuddyPress Docs | Boone B Gorges, David Cavins 2.1.2
BuddyPress Edit Activity | BuddyBoss 1.0.9
BuddyPress First Letter Avatar | Dev49.net 2.2.8
BuddyPress Follow | Andy Peatling, r-a-y 1.2.2
BuddyPress Global Search | BuddyBoss 1.1.9
BuddyPress Group Email Subscription | Deryk Wenaus, boonebgorges, r-a-y 3.9.2
BuddyPress Groups Extras | slaFFik 3.6.9.1
BuddyPress Sitewide Activity Widget | BuddyDev 1.3.5
BuddyPress Xprofile Custom Fields Type | donmik 2.4.4
BuddyPress | The BuddyPress Community 4.2.0
Disable Gutenberg | Jeff Starr 1.7
GD bbPress Attachments | Milan Petrovic 3.1
Hide Admin Bar From Non-admins | Stranger Studios 1.0
Invite Anyone | Boone Gorges 1.4.0
Jetpack by WordPress.com | Automattic 7.2.1
Current Year and Copyright Shortcodes | David Gewirtz 1.0.2
WPBakery Page Builder | Michael M - WPBakery.com 5.7
K Elements | SeventhQueen 4.3.5.1
Modern Events Calendar | Webnus Team 2.8.0
Paid Memberships Pro | Stranger Studios 2.0.4
Paid Memberships Pro - Add Member From Admin | Stranger Studios .5
Paid Memberships Pro - bbPress Add On | Stranger Studios, Scott Sousa 1.5.5
Paid Memberships Pro - BuddyPress Add On | Paid Memberships Pro 1.2.1
Regenerate Thumbnails | Alex Mills (Viper007Bond) 3.1.0
Slider Revolution | ThemePunch 5.4.8.2
Simple Buddypress Profile Privacy | Justin Hansen 0.7.8
Subscribe To Comments | Mark Jaquith 2.3
System Snapshot Report | Reaktiv Studios 1.0.1
User Switching | John Blackbourn & contributors 1.5.0
WC Fields Factory | Saravana Kumar K 3.0.3
Checkout Field Editor for WooCommerce | ThemeHiGH 1.3.1
WooCommerce Blocks | Automattic 2.0.0
NextMove - WooCommerce Thank You Page Lite | XLPlugins 2.9.3
TeraWallet | WCBeginner 1.3.6
WooCommerce Offline Gateway | SkyVerge 1.0.2
WooCommerce Services | Automattic 1.19.0
WooCommerce | Automattic 3.6.1
WordPress Social Login | Miled 2.3.3
Wordpress File Upload | Nickolas Bossinas 4.11.1
WP Post Popup | Allure Web Solutions 3.2.1
WP System Info | Nurul Amin 1.2
WPForms Lite | WPForms 1.5.2.2
WPS Hide Login | WPServeur, NicolasKulka, tabrisrp 1.5.2.1

![2019-04-20_10-22-25](https://user-images.githubusercontent.com/49816006/56459408-c717ac00-6358-11e9-8703-050e1247d7cc.png)

**Comment by Venutius** [comment]
Hi Jon, thanks for testing this. Since you posted on bp.org I noticed there was a typo in my last update. If you download it again it should now work. One thing to note is that currently it stores the login name of the selected user in the field data.

**Comment by JonAllenTX** [comment]
OK thanks.

**Comment by JonAllenTX** [comment]
That did the trick.  Thanks!
